name: ci

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

env:
  GO_VERSION: 1.18

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          version: latest
          args: --fast
          # skip cache because of flaky behaviors
          skip-build-cache: true
          skip-pkg-cache: true
      - name: Test
        run: |
          go test -race -coverprofile coverage.out -covermode=atomic ./...
          go tool cover -func=coverage.out